### ISSUE TITLE
validation problem in Landa.xml

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfc-nusantara-epigraphy#34]
@ajaniak:

this concerns the file DHARMA_INSIDENKLanda.xml.

screenshot:

<img width="1497" alt="Capture d’écran 2021-02-27 à 08 29 19" src="https://user-images.githubusercontent.com/835603/109379752-8edb4000-78d6-11eb-95e7-d182df62d121.png">

do you understand what is causing the file to invalidate? I don't really grasp the meaning of the ! message at the bottom of my screen.

**Comment by ajaniak** [comment]
The error message implies either that there was an issue regarding Github server two days ago (I don't have it right now, so it might be solved), either there is an issue in the connexion between your oxygen and Github Server; if so Oxygen should warn you, but not trough the validation system of the XML files. 
Can you check if you still have the error message today?

**Comment by arlogriffiths** [comment]
yes, I still have the error today


Le 1 mars 2021 à 11:44, ajaniak <notifications@github.com<mailto:notifications@github.com>> a écrit :



The error message implies either that there was an issue regarding Github server two days ago (I don't have it right now, so it might be solved), either there is an issue in the connexion between your oxygen and Github Server; if so Oxygen should warn you, but not trough the validation system of the XML files.
Can you check if you still have the error message today?

**Comment by ajaniak** [comment]
First, we will make sure that your Oxygen is correctly configurated. Can you send me a screenshoot for your list of trusted host? Preferences > Network Connection Settings > Trusted Hosts
As well as the Schematron set up: Preferences > XML > XML Parser > Schematron. 

It might come form the set up of your computer itself probably regarding proxies.  I will try to solve with issue using another service than raw.githubusercontents, otherwise I would need to check the set up of your computer more deeply.

**Comment by arlogriffiths** [comment]
The problem occurred suddenly starting a few days ago, and seems to occur both on my side and Marine's (maybe for other people too, who haven't been looking at Oxygen for a while).

Here are my screenshots:

<img width="991" alt="Capture d’écran 2021-03-01 à 13 07 12" src="https://user-images.githubusercontent.com/835603/109495190-369b6e00-7a8f-11eb-89cd-e9a0a6535cd9.png">

<img width="990" alt="Capture d’écran 2021-03-01 à 13 10 08" src="https://user-images.githubusercontent.com/835603/109495363-79f5dc80-7a8f-11eb-87ea-68b286e55bd4.png">

**Comment by m-schoettel** [comment]
I have the same problem of validation. Here are my screenshots:

<img width="1086" alt="Screenshot 2021-03-01 at 13 08 01" src="https://user-images.githubusercontent.com/26002486/109495551-bb868780-7a8f-11eb-8d7a-7b1e8fa4f71a.png">


<img width="1121" alt="Screenshot 2021-03-01 at 13 09 02" src="https://user-images.githubusercontent.com/26002486/109495560-be817800-7a8f-11eb-9637-5f58cf740dce.png">

Thanks in advance for your help!

**Comment by ajaniak** [comment]
Your schematron set up is fine for what we are doing. However, not all hosts used for schematron and raw.githubusercontent are appearing in Arlo's and none of them are in Marine's. 

If it worked before, and since no changes were made in the schemas, I wonder about: 
- have you update oxygen or your OS? 
- does it happen for Landa and Batur files only or do you have it for all your files? 
- is it always the same error message? 

Ok, I have migrated the system calling to another service. I am pushing it on the server, but it might need a little time to be applied (up to 2 hours). Let me know, if it changes something. 

@m-schoettel, would you have time this week so I can take a look at your computer directly?

**Comment by arlogriffiths** [comment]
Dear Axelle,

Thanks.

I have not recently updated oxygen or my system.
It is happening to most but not all of the ca. 10 xml files I currently have open.
It’s always the same message.

Let’s hope your operation has the desired effect!

Best,

Arlo


Le 1 mars 2021 à 16:32, ajaniak <notifications@github.com<mailto:notifications@github.com>> a écrit :



Your schematron set up is fine for what we are doing. However, not all hosts used for schematron and raw.githubusercontent are appearing in Arlo's and none of them are in Marine's.

If it worked before, and since no changes were made in the schemas, I wonder about:

  *   have you update oxygen or your OS?
  *   does it happen for Landa and Batur files only or do you have it for all your files?
  *   is it always the same error message?

Ok, I have migrated the system calling to another service. I am pushing it on the server, but it might need a little time to be applied (up to 2 hours). Let me know, if it changes something.

@m-schoettel<https://github.com/m-schoettel>, would you have time this week so I can take a look at your computer directly?

**Comment by ajaniak** [comment]
Chers tous les deux, 

Could you check your java version please? Oxygen requires a JDK 1.8 to run smoothly and the schema connexion is based on Event Dispatch Thread of java 8. 

To check it, go to preferences of your mac. The icon should be there at the bottom of the window. 
<img width="781" alt="Capture d’écran 2021-03-03 à 15 00 53" src="https://user-images.githubusercontent.com/33328906/109816815-74d09300-7c31-11eb-8396-b1190eb7d2de.png">

Launch it, and check the second tab for updates and update it if any updates are available or if you are not on version 8.

**Comment by arlogriffiths** [comment]
The same kind of problem is still occurring. Just the URL that is "not available" has changed. See screenshot.

<img width="1564" alt="Capture d’écran 2021-03-31 à 07 38 22" src="https://user-images.githubusercontent.com/835603/113095668-242e6480-91f4-11eb-82c8-e434d6a0d612.png">
