### ISSUE TITLE
revise Maribong.xml

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfc-nusantara-epigraphy#4]
Eko: I have gone through your file, made some silent changes but inserted quite a few comments marked like this `<!-- Arlo: ... -->`. Please go through them and carry out the needed changes, removing the comments after you have executed them.

Answer to this issue once you'are done.

Axelle and Dan: if you could take a look once Eko is done, that would be great.

**Comment by danbalogh** [comment]
I've had a look at the file. All looks good to me; the only problem I've spotted is the reference Nurhadi Magetsari+al1979_01, from which the space needs to be deleted.

**Comment by arlogriffiths** [comment]
Eko:  I am happy to see that you have mastered the technique of closing an issue by using the right commit message. But I had asked you to let us know when you were not, not to close the issue :) So I am reopening it now.

Dan: thanks. Could you confirm that what Eko has done at the end of the text is alright? This is the first and only plate of what was originally a multiplate set. I am wondering if we should have something like `<gap reason="lost" extent="unknown" unit="plate">`. I suppose we have some guidance on what to do in such a case in the EG, but I cannot easily find it.

Axelle: could you take a look at the file too?

**Comment by danbalogh** [comment]
Good point, I wasn't paying enough attention. The EG does have instructions for "lost copper plates" and "massive lacunae" (under §5.4), but actually some of the latter is not quite clear.
My basic attitude is that there is no point in encoding the lost plate: I have thought of that and rejected the idea because it does not serve a useful function. The fact will be mentioned in the metadata and is only important to human readers.
What should definitely be done is:
1. delete the hyphen from ri- at the end of the extant text.
2. add @part="I" (for "initial part") to the last <p> element in the extant text, to encode the fact that this is an incomplete paragraph.

After this, there are basically two options as per the present state of the EG:
1. make no further changes. I prefer this simpler solution.
or 2. instead of mentioning the apparatus, encode "ripta" as a restoration. But if this is done, then the second page does need to be encoded as per the EG section on massive lacunae:
ri
<pb n="2r"/><lb n="1"/><supplied reason="lost">pta</supplied></p><gap reason="lost" extent="unknown" unit="character"/>
<gap reason="lost" extent="unknown" unit="line"/>

Do you agree with the above approach? I think option 2 should be limited to cases with a more substantial restoration. If you agree, I'll make that explicit in the guide, noting that short or uncertain restorations should be mentioned in the apparatus instead of all that code.
I'll also make it clearer under "Lost copper plates" that option 2 is available, since it is only discussed under "Massive lacunae" (to which "Lost copper plates" refers, but that is a bit vague at the moment).

**Comment by ajaniak** [comment]
I have taken a look, you already have spotted the issues for the point not aligned on the EG.

**Comment by arlogriffiths** [comment]
@ajaniak : thanks.

@danbalogh : thanks also. I agree with option 1.

@ekobastiawan : please carry out my corrections suggested in the file, as well as Dan's correction indicated above, and the close this issue.

**Comment by danbalogh** [comment]
Arlo, just to be clear: options 1 and 2 are both there in the EG, not as options, but as "if there is no restoration" and "if there is restoration". The question, apart from the issue at hand is: should I point it out in the Guide that short and simple restorations may be treated as "no restoration" and handled in the apparatus instead of the edition. Please confirm you agree with that in general.

**Comment by arlogriffiths** [comment]
I confirm.

Le 21 janv. 2020 à 18:41, danbalogh <notifications@github.com<mailto:notifications@github.com>> a écrit :


Arlo, just to be clear: options 1 and 2 are both there in the EG, not as options, but as "if there is no restoration" and "if there is no restoration". The question, apart from the issue at hand is: should I point it out in the Guide that short and simple restorations may be treated as "no restoration" and handled in the apparatus instead of the edition. Please confirm you agree with that in general.

**Comment by arlogriffiths** [comment]
Eko: I have revised the file one last time. Please go through it and close this issue when you're done. (You can try git commit -m "resolves #4" once again!)
