### ISSUE TITLE
Merge subfolders

### ISSUE THREAD

**Issue by manufrancis** [erc-dharma/tfc-nusantara-epigraphy#42]
Same suggestions as for "tfc-khmer-epigraphy".
See https://github.com/erc-dharma/tfc-khmer-epigraphy/issues/24

**Comment by arlogriffiths** [comment]
the subfolders help us organize our research, and are particularly useful as long as we don’t have IDENK inventory numbers yet, and for this reason the case feels somewhat different from the case of "tfc-khmer-epigraphy". so it’s a matter of balancing the convenience of our team against the convenience of Axelle’s system mnanagement. since I don’t know the nature of the problems she is facing, and how difficult/urgent they are, it’s hard for me to decide which is more important.


Le 9 avr. 2021 à 10:45, manufrancis ***@***.******@***.***>> a écrit :



Same suggestions as for "tfc-khmer-epigraphy".
See erc-dharma/tfc-khmer-epigraphy#24<https://github.com/erc-dharma/tfc-khmer-epigraphy/issues/24>
