### ISSUE TITLE
DHARMA_INSIDENKMarinci_II _ 

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-nusantara-epigraphy#49]
Dear @m-schoettel  and @arlogriffiths, 

In your edition Marinci II, an attribute `@source` is missing on a `<rdg>` element. Can you see if it can be provided? If not let us know so that the EGC rules are updated to match any special case. 

```
<app loc="1r1">
               <lem>paramb<unclear>ə</unclear><lb break="no"/>kəl·</lem>
               <rdg>parambikəl</rdg>
             </app>
```

Thanks

**Comment by m-schoettel** [comment]
I have found the short title for BPA 47 and added it in the rdg. Thanks @ajaniak!

**Comment by arlogriffiths** [comment]
It seems you haven't yet added MachiSuhadi+RichadianaKartakusuma1996_01 to your file's bibliography.

Please make sure the apparatus is fully positive (which it doesn't seem to be at the moment), unless there is a reason to make an exeption to the general rule that our apparatuses are positive.

**Comment by arlogriffiths** [comment]
And think of adding a `<change>` line when making significant changes to your files, e.g. when you're resolving invalidity problems such as those pointed out by Axelle.

**Comment by m-schoettel** [comment]
Understood. I have now changed the file's bibliography <div>. 
In order to make a positive apparatus I would need to record the readings in Issatriadi 1975, which is the Zotero library but which I have not been able to find this publication myself (nor is it in the DHARMA sharedocs).

I am waiting to close this issue for now.
